name: ExtUtils-FakeConfig
abstract: overrides some configuration values
author: Mattia Barbon <mbarbon@cpan.org>
version: 0.08
license: perl
distribution_type: module
requires:
    File::Spec: 0
build_requires:
  Test::More: 0.48
dynamic_config: 1
generated_by: Mattia Barbon, by hand
